# -*- coding: utf-8 -*-
"""TP Estructuras Condicionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4dG1KdnRNVmM7TmwymqdBDN9gaBmYHH
"""

# 1) Escribir un programa que solicite la edad del usuario. Si el usuario es mayor de 18 años,
# deberá mostrar un mensaje en pantalla que diga “Es mayor de edad”.

#solicito la edad al usuario, y me aseguro de que sea un número entero
edad = int(input("Ingrese su edad: "))

#si edad es mayor a 18, imprimo el mensaje.
if edad > 18:
  print("Es mayor de edad")
#si no es mayor indico al progrma no hacer nada
else:
  pass

# 2) Escribir un programa que solicite su nota al usuario. Si la nota es mayor o igual a 6, deberá
# mostrar por pantalla un mensaje que diga “Aprobado”; en caso contrario deberá mostrar el mensaje
# “Desaprobado”.

#solicito al usuario que ingrese la nota. La nota puede ser decimal.
nota = float(input("Ingrese su nota: "))

if nota >= 6:
  print("Aprobado")
else:
  print("Desaprobado")

# 3) Escribir un programa que permita ingresar solo números pares. Si el usuario ingresa un número par,
# imprimir por en pantalla el mensaje "Ha ingresado un número par"; en caso contrario, imprimir por
# pantalla "Por favor, ingrese un número par".
# Nota: investigar el uso del operador de módulo (%) en Python para evaluar si un número es par o impar.

#solicito al usuario que ingrese un número entero
numero = int(input("Ingrese un número entero: "))

# El módulo (%) permite determinar si un número es par o impar. Cuando el módulo 2 de un número es 0
# entonces es par. Si el módulo 2 de un número es 1 entonces es impar. Esto tiene que ver con que
# todo número par es divisible por dos, y su división no tiene resto.

if numero % 2 == 0:
  print("Ha ingresado un número par")
else:
  print("Por favor, ingrese un número par")

# 4) Escribir un programa que solicite al usuario su edad e imprima por pantalla a cuál de las siguientes
# categorías pertenece:
# •Niño/a: menor de 12 años.
# •Adolescente: mayor o igual que 12 años y menor que 18 años.
# •Adulto/a joven: mayor o igual que 18 años y menor que 30 años.
# •Adulto/a: mayor o igual que 30 años.

#solicito la edad al usuario
edad = int(input("Ingrese su edad: "))

if edad < 12:
  print("Usted pertenece a la categoría Niño/a")
elif edad >= 12 and edad < 18:
  print("Usted pertenece a la categoría Adolescente")
elif edad >= 18 and edad < 30:
  print("Usted pertenece a la categoría Adulto/a joven")
else
  print("Usted pertenece a la categoría Adulto/a")

# 5) Escribir un programa que permita introducir contraseñas de entre 8 y 14 caracteres (incluyendo 8 y 14). Si el usuario
# ingresa una contraseña de longitud adecuada, imprimir por en pantalla el mensaje "Ha ingresado una contraseña correcta";
# en caso contrario, imprimir por pantalla "Por favor, ingrese una contraseña de entre 8 y 14 caracteres".
# Nota: investigue el uso de la función len() en Python para evaluar la cantidad de elementos que tiene un iterable tal como
# una lista o un string.

contrasena = input("Por favor ingrese una contraseña entre 8 y 14 caracteres: ")

# Para este caso, la función len() nos permite conocer la cantidad de caracteres de la cadena ingresada
longitud = len(contrasena)

if longitud >= 8 and longitud <= 14:
  print("Ha ingresado una contraseña correcta")
else:
  print("Por favor, ingrese una contraseña de entre 8 y 14 caracteras")

# 6) Escribir un programa que solicite al usuario el consumo mensual de energía eléctrica en kilovatios (kWh) e indique la categoría
# del consumo según el siguiente criterio:
# • Menor que 150 kWh: “Consumo bajo”.
# • Entre 150 y 300 kWh (inclusive): “Consumo medio”.
# • Mayor que 300 kWh: “Consumo alto”.
# Además, si el consumo supera los 500 kWh, mostrar un mensaje adicional que diga: “Considere medidas de ahorro energético”.
# El programa debe imprimir por pantalla la categoría correspondiente.

consumo_energetico = float(input("Ingrese el consumo mensual de energía eléctrica en Kilovatios (KWh): "))

if consumo_energetico < 150:
  print("Consumo bajo.")
elif consumo_energetico >= 150 and consumo_energetico <= 300:
  print("Consumo medio.")
else:
  print("Consumo alto.")
  if consumo_energetico > 500:
    print("Considere medidas de ahorro energético")

#7) Escribir un programa que solicite una frase o palabra al usuario. Si el string ingresado termina con vocal,
# añadir un signo de exclamación al final e imprimir el string resultante por pantalla; en caso contrario, dejar
# el string  tal cual lo ingresó el usuario e imprimirlo por pantalla.

frase_palabra = input("Ingrese una frase o palabra: ")

#con strip(): me aseguro de eliminar espacios en blanco al final para que no de un resultado erroneo
#con [-1]: accedo a la última letra de la frase/palabra ingresada
#lower():convierto la letra a minúscula por si el usuario ingresó mayúsculas, y reduzco las vocales a evaluar

if frase_palabra.strip()[-1].lower() in 'aeiou':
  print(frase_palabra+"!")
else:
  print(frase_palabra)

# 8) Escribir un programa que solicite al usuario que ingrese su nombre y el número 1, 2 o 3 dependiendo de la opción que desee:
# 1.Si quiere su nombre en mayúsculas. Por ejemplo: PEDRO.
# 2.Si quiere su nombre en minúsculas. Por ejemplo: pedro.
# 3.Si quiere su nombre con la primera letra mayúscula. Por ejemplo: Pedro.
# El programa debe transformar el nombre ingresado de acuerdo con la opción seleccionada por el usuario e imprimir el resultado por
# pantalla. Nota: investigue uso de las funciones upper(), lower() y title() de Python para convertir entre mayúsculas y minúsculas.

nombre =  input("Por favor, ingrese su nombre: ")

print(f"""Qué operación desea realizar?:
1.Quiere su nombre en mayúsculas
2.Quiere su nombre en minúsculas
3.Queire su nombre con la primera letra mayúscula""")

opcion =  int(input("Ingrese una opción: "))

if opcion == 1:
  # upper(): convierte una cadena a mayúsculas
  print(nombre.upper())
elif opcion == 2:
  # lower(): convierte una cadena a minúsculas
  print(nombre.lower())
elif opcion == 3:
  # title(): convierte la primera letra de una cadena a mayúscula
  print(nombre.title())
else:
  pass

#9) Escribir un programa que pida al usuario la magnitud de un terremoto, clasifique la magnitud en una de las siguientes categorías
# según la escala de Richter e imprima el resultado por pantalla:
# •Menor que 3: "Muy leve" (imperceptible).
# •Mayor o igual que 3 y menor que 4: "Leve" (ligeramente perceptible).
# •Mayor o igual que 4 y menor que 5: "Moderado" (sentido por personas, pero generalmente no causa daños).
# •Mayor o igual que 5 y menor que 6: "Fuerte" (puede causar daños en estructuras débiles).
# •Mayor o igual que 6 y menor que 7: "Muy Fuerte" (puede causar daños significativos).
# •Mayor o igual que 7: "Extremo" (puede causar graves daños a gran escala).

magnitud = float(input("Ingrese la magnitud del terremoto: "))

if magnitud < 3:
  print("Muy leve (imperceptible)")
elif magnitud >= 3 and magnitud < 4:
  print("Leve (ligeramente perceptible)")
elif magnitud >= 4 and magnitud < 5:
  print("Moderado (sostenido por personas, pero generalmente no causa daños)")
elif magnitud >= 5 and magnitud < 6:
  print("Fuerte (puede causar daños en estructuras débiles)")
elif magnitud >= 6 and magnitud < 7:
  print("Muy Fuerte (puede causar daños significativos)")
else:
  print("Extremo (puede causar graves daños a gran escala)")

# Escribir un programa que pregunte al usuario en cuál hemisferio se encuentra (N/S), qué mes del año es y qué día es.
# El programa deberá utilizar esa información para imprimir por pantalla si el usuario se encuentra en otoño, invierno,
# primavera o verano. hemisferio

hemisferio = input("Indique en qué hemisferio se encuentra?. Norte(n)/Sur(s): ").lower()
mes = int(input("Ingrese el mes en número:" ))
dia = int(input("Ingrese el día en números:"))


# Valido los datos ingresados por el usuario para prevenir algunos errores.
if (dia <= 0 or dia >31) or (mes <= 0 or mes >12) or (hemisferio not in ('s','n')):
  print("Los datos ingresados no son correctos, por favor verifique y vuelva a ingresar.")
else:
  # Evalúo la estación para el hemisferio norte, y establezco la estación.
  # del 21/12 al 20/03 Invierno en H.Norte
  if (mes == 12 and dia >= 21) or mes in (1, 2) or (mes == 3 and dia <= 20):
      estacion = "Invierno"
  # del 21/03 al 20/06 Primavera en H.Norte
  elif (mes == 3 and dia >= 21) or mes in (4, 5) or (mes == 6 and dia <= 20):
      estacion = "Primavera"
  # del 21/06 al 20/09 Verano en H.Norte
  elif (mes == 6 and dia >= 21) or mes in (7, 8) or (mes == 9 and dia <= 20):
      estacion = "Verano"
  # cualquier otro caso debe estar comprendido del 21/09 al 20/12 Otoño en H.Norte
  else:
      estacion = "Otoño"

  # Si el hemisferio ingresado por el usuario es norte 'n', imprimo la estación,
  # Si el hemisferio ingresado fue sur 's', entonces invierto la estación y la impirimo
  if hemisferio == 'n':
    print(estacion)
  elif estacion == 'Invierno':
    print("Verano")
  elif estacion == 'Primavera':
    print("Otoño")
  elif estacion == 'Verano':
    print("Invierno")
  else:
    print("Primavera")